# Generated by Django 5.0.6 on 2024-07-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_topping_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(default='For the love of satisfaction and sweetness'),
        ),
    ]
