# Generated by Django 5.0.6 on 2024-07-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_pizza_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'pizzas'},
        ),
    ]
